# Generated by Django 5.2.7 on 2025-11-05 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('depreciation_rate', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Consignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Indenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IssueRequisiton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisiton_no', models.CharField(max_length=64)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('purpose', models.CharField(max_length=255, null=True)),
                ('issued_by', models.CharField(blank=True, max_length=255, null=True)),
                ('received_by', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('ISSUED', 'Issued'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_type', models.CharField(choices=[('CONSUMABLE', 'Consumable'), ('DEADSTOCK', 'Deadstock'), ('EQUIPMENT', 'Equipment')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_no', models.CharField(max_length=128, unique=True)),
                ('contract_date', models.DateField()),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ams.contractor')),
            ],
        ),
        migrations.CreateModel(
            name='Indent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indent_no', models.CharField(max_length=128, unique=True)),
                ('indenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ams.indenter')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('issued_to', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_delivery', models.DateField(blank=True, null=True)),
                ('delivery_status', models.CharField(blank=True, max_length=16, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ams.consignee')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ams.contract')),
                ('indent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ams.indent')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('specifications', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ams.category')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acct_unit', models.CharField(blank=True, max_length=64, null=True)),
                ('tendered_quantity', models.IntegerField(default=0)),
                ('rejected_quantity', models.IntegerField(default=0)),
                ('accepted_quantity', models.IntegerField(default=0)),
                ('rejected_reason', models.TextField(blank=True, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('gst_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generate_qr_code', models.BooleanField(default=False)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ams.inspectioncertificate')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_items', to='ams.item')),
                ('stock_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_items', to='ams.stockregister')),
            ],
        ),
        migrations.CreateModel(
            name='ItemInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('status', models.CharField(choices=[('IN_STOCK', 'In Stock'), ('ISSUED', 'Issued'), ('UNDER_REPAIR', 'Under Repair'), ('DISPOSED', 'Disposed'), ('LOST', 'Lost')], default='IN_STOCK', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_instances', to='ams.inspectioncertificate')),
                ('inspection_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_instances', to='ams.inspectionitem')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='ams.item')),
            ],
        ),
        migrations.CreateModel(
            name='IssueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acct_unit', models.CharField(max_length=255, null=True)),
                ('quantity_required', models.IntegerField(default=1)),
                ('quantity_recieved', models.IntegerField(default=1)),
                ('major_head', models.CharField(max_length=255, null=True)),
                ('store_post_reference', models.CharField(max_length=300, null=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ams.issuerequisiton')),
                ('item_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_items', to='ams.iteminstance')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('responsible_person', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sublocations', to='ams.location')),
            ],
        ),
        migrations.AddField(
            model_name='iteminstance',
            name='current_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_instances', to='ams.location'),
        ),
        migrations.AddField(
            model_name='issuerequisiton',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ams.location'),
        ),
        migrations.AddField(
            model_name='inspectioncertificate',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_certificates', to='ams.location'),
        ),
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_entry', models.DateField(auto_now_add=True)),
                ('voucher_no', models.CharField(blank=True, max_length=128, null=True)),
                ('entry_type', models.CharField(choices=[('RECIEVED', 'Recieved'), ('ISSUE', 'Issue'), ('ADJUSTMENT', 'Adjustment')], max_length=20)),
                ('quantity_in', models.IntegerField(default=0)),
                ('quantity_out', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('balance', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_entries', to='ams.inspectioncertificate')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='ams.item')),
                ('stock_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='ams.stockregister')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to='ams.location')),
            ],
        ),
        migrations.AddField(
            model_name='stockregister',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_registers', to='ams.store'),
        ),
        migrations.AddField(
            model_name='iteminstance',
            name='current_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_instances', to='ams.store'),
        ),
    ]
