# Generated by Django 5.2.7 on 2025-11-05 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockentry',
            name='issue',
        ),
        migrations.RenameField(
            model_name='issueitem',
            old_name='quantity',
            new_name='quantity_recieved',
        ),
        migrations.RemoveField(
            model_name='issueitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='issueitem',
            name='remarks',
        ),
        migrations.AddField(
            model_name='issueitem',
            name='acct_unit',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='issueitem',
            name='item_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_items', to='ams.iteminstance'),
        ),
        migrations.AddField(
            model_name='issueitem',
            name='major_head',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='issueitem',
            name='quantity_required',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issueitem',
            name='store_post_reference',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='entry_type',
            field=models.CharField(choices=[('RECIEVED', 'Recieved'), ('ISSUE', 'Issue'), ('ADJUSTMENT', 'Adjustment')], max_length=20),
        ),
        migrations.CreateModel(
            name='IssueRequisiton',
            fields=[
                ('requisiton_no', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('purpose', models.CharField(max_length=255, null=True)),
                ('issued_by', models.CharField(blank=True, max_length=255, null=True)),
                ('received_by', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ams.location')),
            ],
        ),
        migrations.AlterField(
            model_name='issueitem',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ams.issuerequisiton'),
        ),
        migrations.DeleteModel(
            name='IssueTransaction',
        ),
    ]
